services:
  nginx-local-ip:
    container_name: nginx-local-ip 
    image: medicmobile/nginx-local-ip
    build: .
    ports:
      - "${HTTP}:80"
      - "${HTTPS}:443"
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      APP_URL: $APP_URL
      HTTP: $HTTP
      HTTPS: $HTTPS
      CERT_PEM_SRC: ${CERT_PEM_SRC:-https://local-ip.medicmobile.org/cert}
      CERT_CHAIN_SRC: ${CERT_CHAIN_SRC:-https://local-ip.medicmobile.org/chain}
      CERT_KEY_SRC: ${CERT_KEY_SRC:-https://local-ip.medicmobile.org/key}
      DOMAIN: ${DOMAIN:-local-ip.medicmobile.org}

networks:
  default:
    ipam:
      config:
        # Useful for ensuring the assigned network address is within the range configured for your firewall rules
        - subnet: 172.16.0.0/16
