app:
  build: .
  ports:
    - "${HTTP}:80"
    - "${HTTPS}:443"
  volumes:
    - ./default.conf.template:/etc/nginx/templates/default.conf.template
    - ./entrypoint.sh:/entrypoint.sh
  environment:
    APP_URL: $APP_URL
