version: "3.7"

services:
  nginx-local-ip:
    container_name: nginx-local-ip 
    image: medicmobile/nginx-local-ip
    build: .
    ports:
      - "${HTTP}:80"
      - "${HTTPS}:443"
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - ./base-path.json:/usr/share/nginx/base-path.json
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      APP_URL: $APP_URL
      HTTP: $HTTP
      HTTPS: $HTTPS

networks:
  default:
    ipam:
      config:
        - subnet: 172.16.0.0/16
